// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCivbMLlzE8TOB275xanPF4V-DsMk0H2WE',
    appId: '1:268452201321:web:8d771a3aabeff1058bb3f8',
    messagingSenderId: '268452201321',
    projectId: 'my-book-finder-fe43a',
    authDomain: 'my-book-finder-fe43a.firebaseapp.com',
    storageBucket: 'my-book-finder-fe43a.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrnbAnZkD4BBd8RrxdCSySIQFzH25K96A',
    appId: '1:268452201321:android:967210eafc86399b8bb3f8',
    messagingSenderId: '268452201321',
    projectId: 'my-book-finder-fe43a',
    storageBucket: 'my-book-finder-fe43a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBldtq5RoWHaq9ZcAqXTfE_kBYNJHeEO-w',
    appId: '1:268452201321:ios:d0b7b749c3810fa78bb3f8',
    messagingSenderId: '268452201321',
    projectId: 'my-book-finder-fe43a',
    storageBucket: 'my-book-finder-fe43a.appspot.com',
    iosClientId: '268452201321-m9f02utco4id5dbj27fs624bnsn2sadg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookFinder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBldtq5RoWHaq9ZcAqXTfE_kBYNJHeEO-w',
    appId: '1:268452201321:ios:d0b7b749c3810fa78bb3f8',
    messagingSenderId: '268452201321',
    projectId: 'my-book-finder-fe43a',
    storageBucket: 'my-book-finder-fe43a.appspot.com',
    iosClientId: '268452201321-m9f02utco4id5dbj27fs624bnsn2sadg.apps.googleusercontent.com',
    iosBundleId: 'com.example.myBookFinder',
  );
}
